defaults: &defaults
  host: localhost
  database: redcity
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  # host: flame.mongohq.com
  # host: flame.mongohq.com
  # port: 27057
  # username: app
  # password: secret
  port: 27017
  database: redcity-development

test:
  <<: *defaults
  host: localhost
  database: redcity_test

# set these environment variables on your prod server
production:
  database: redcity-development
  # host: flame.mongohq.com
  # port: 27055
  # username: app
  # password: secret
  # database: redcity  
  
  # host: <%= ENV['MONGOID_HOST'] %>
  # port: <%= ENV['MONGOID_PORT'] %>
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  # database: <%= ENV['MONGOID_DATABASE'] %>